More backward compatible with version 3
camptocamp/c2cwsgiutils pull request #822
Opened 2020-12-15 13:26 UTC by fredj

2020-12-15 15:23 UTC, sbrunner commented on c2cwsgiutils/errors.py
> +        _utils.env_or_config(config, "C2C_ENABLE_EXCEPTION_HANDLING", "c2c.enable_exception_handling", "1")
This is not compatible with release 4!

2020-12-15 16:00 UTC, fredj commented on c2cwsgiutils/errors.py
> +        _utils.env_or_config(config, "C2C_ENABLE_EXCEPTION_HANDLING", "c2c.enable_exception_handling", "1")
The [README](https://github.com/camptocamp/c2cwsgiutils/blob/release_4/README.md#exception-handling) says that: "By default, c2cwsgiutils will install exception handling views [...]"

2020-12-15 16:09 UTC, gberaudo approved these changes
Thanks @fredj, will greatly ease migration to v4. LGTM.

2020-12-15 16:22 UTC, sbrunner commented on c2cwsgiutils/errors.py
> +        _utils.env_or_config(config, "C2C_ENABLE_EXCEPTION_HANDLING", "c2c.enable_exception_handling", "1")
Then the README should be updated...

2020-12-15 16:46 UTC, gberaudo commented on c2cwsgiutils/errors.py
> +        _utils.env_or_config(config, "C2C_ENABLE_EXCEPTION_HANDLING", "c2c.enable_exception_handling", "1")
@sbrunner, since the contract in c2cwsgiutil4 is not clear I would rather go with resolving the case by staying compatibile with v3.

What was the reason to return HTML errors by default instead of JSON?

2020-12-15 17:05 UTC, sbrunner commented on c2cwsgiutils/errors.py
> +        _utils.env_or_config(config, "C2C_ENABLE_EXCEPTION_HANDLING", "c2c.enable_exception_handling", "1")
How is the contract in c2cwsgiutil4 not clear? 

We disable that by default because it breaks some application and the more value is relay low...

2020-12-15 17:06 UTC, sbrunner requested changes
Exception_handling should be disabled by default

2020-12-16 11:00 UTC, arnaud-morvan commented
Note that in cornice exception handling is activated by default : https://cornice.readthedocs.io/en/latest/faq.html#cornice-registers-exception-handlers-how-do-i-deal-with-it
For me this depends on : are projets using c2cwsgiutils REST APIs or not ?

2020-12-16 11:27 UTC, gberaudo commented
Thanks for the feedbacks. The status here is that we will remove the part about the exception handler.
Then we need to choose whether to rebase this PR on release_4 or not. This depends of the presence of some backward incompatible stuffs in master right now, @sbrunner, thoughts?.

2020-12-16 11:38 UTC, sbrunner commented
+1 :-)

2020-12-16 12:53 UTC, sbrunner approved these changes
Thanks :-)

2020-12-16 13:15 UTC, merged