Alwayse use env_or_config or env_or_settings to correctly handle empt…
camptocamp/c2cwsgiutils pull request #854
Opened 2021-01-05 13:07 UTC by sbrunner

…y environment variable

fix #852 and #837

2021-01-05 13:57 UTC, gberaudo requested changes

2021-01-05 13:57 UTC, gberaudo commented on c2cwsgiutils/profiler.py
> +PATH = c2cwsgiutils.utils_.env_or_settings(None, "C2C_PROFILER_PATH", None, "")
It looks wrong to me to use env_or_settings without passing some settings.

2021-01-05 13:57 UTC, gberaudo commented on .prospector.yaml
> +    - wrong-import-order
Is there a good and wrong import order in python or is it only pedantic change?

2021-01-05 13:57 UTC, gberaudo commented on c2cwsgiutils/redis_utils.py
> +def get(settings) -> Tuple[Optional[redis.Redis], Optional[redis.Redis], Optional[redis.sentinel.Sentinel]]:
This looks like a breaking change.

2021-01-05 13:57 UTC, gberaudo commented on c2cwsgiutils/broadcast/__init__.py
> +from c2cwsgiutils import redis_utils, utils_
I guess _util was used to avoid conflicting with the utils package.
What about calling it `config_util`?

2021-01-05 14:02 UTC, sbrunner commented on .prospector.yaml
> +    - wrong-import-order
No, and we can't have tow different tools to check the import order, then I disable the pylint check...

2021-01-05 14:02 UTC, sbrunner commented on c2cwsgiutils/redis_utils.py
> +def get(settings) -> Tuple[Optional[redis.Redis], Optional[redis.Redis], Optional[redis.sentinel.Sentinel]]:
+1, changing :-)

2021-01-05 14:03 UTC, sbrunner commented on c2cwsgiutils/broadcast/__init__.py
> +from c2cwsgiutils import redis_utils, utils_
+1 :-)

2021-01-05 14:05 UTC, sbrunner commented on c2cwsgiutils/profiler.py
> +PATH = c2cwsgiutils.utils_.env_or_settings(None, "C2C_PROFILER_PATH", None, "")
`env_or_settings` works well with a `None` settings, but it's throw that it's not needed here I just do that for coherence...
What do you think?

2021-01-05 14:08 UTC, sbrunner commented on c2cwsgiutils/broadcast/__init__.py
> +from c2cwsgiutils import redis_utils, utils_
with a 's' to be coherent with `redis_utils`

2021-01-05 14:23 UTC, gberaudo commented on c2cwsgiutils/profiler.py
> +PATH = c2cwsgiutils.utils_.env_or_settings(None, "C2C_PROFILER_PATH", None, "")
I would go to simplicity and only use `env_or_settings` in the cases where we actually have settings.

2021-01-05 14:24 UTC, gberaudo commented on .prospector.yaml
> +    - wrong-import-order
Oh, great. But you also changed the import order in some files, right?

2021-01-05 14:48 UTC, gberaudo commented on c2cwsgiutils/pyramid_logging.py
> -        level = os.environ.get("LOG_LEVEL", os.environ.get("OTHER_LOG_LEVEL", "INFO"))
Item

2021-01-05 14:48 UTC, gberaudo commented on c2cwsgiutils/redis_utils.py
> +    settings=None,
Is there some typing we can put here?

2021-01-05 14:55 UTC, sbrunner commented on .prospector.yaml
> +    - wrong-import-order
Yes with isort according the config available in setup.cfg :-)

2021-01-05 15:49 UTC, sbrunner commented
@gberaudo I do all the request changes :-)

2021-01-05 15:54 UTC, gberaudo approved these changes
Thanks

2021-01-06 08:38 UTC, fredj approved these changes
thanks @sbrunner

2021-01-06 09:36 UTC, merged